#!/bin/sh
VERSION="$(fgrep Version opengt.spec |cut -d ' ' -f2)"
RELEASE="$(fgrep Release opengt.spec |cut -d ' ' -f2)"
FILES="$(ls -1 $HOME/RPM/RPMS/i586/*opengt*$VERSION-$RELEASE.i586.rpm $HOME/RPM/RPMS/i586/osolutions-webapps-agp-*$VERSION-$RELEASE.i586.rpm)"

rpmbb opengt.spec || { echo "Build failed. Exit."; exit 1; }
rpm -q opengtd && sudo rpm -Uhv $FILES || sudo rpm -ihv $FILES
sudo service nginx restart

if [ "$1" = "server" ]; then
	rsync -av $FILES map.spo:/tmp/
	ssh="ssh map.spo"
	echo "Update rpm"
	$ssh 'sudo rpm -Uhv /tmp/*.rpm'
#	echo "Remove rpm"
#	$ssh 'sudo rm -f /tmp/*.rpm'
	echo "Restart nginx"
	$ssh 'sudo service nginx restart'
	git push spo
fi
