#!/usr/bin/env python

import socket
from protocols import GlobalsatReport

HOST = ''                 # Symbolic name meaning all available interfaces
PORT = 20100              # Arbitrary non-privileged port
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.bind((HOST, PORT))
s.listen(1)
conn, addr = s.accept()
print 'Connected by', addr
while 1:
	data = conn.recv(1024)
	print u"data: %s" % str(data)
	if not data: break
	gr = GlobalsatReport(str(data))
	print 'lon: %s, lat: %s' % (gr.lon, gr.lat)
	conn.send("$OK!")
conn.close()
