#!/usr/bin/env python
import sys, os
sys.path.insert(1, os.path.join(sys.path[0], '..'))
sys.path.insert(1, os.path.join(sys.path[0], '../opengt'))
sys.path.insert(1, os.path.join(sys.path[0], '../..'))
sys.path.insert(1, os.path.join(sys.path[0], '../../..'))
os.environ['DJANGO_SETTINGS_MODULE'] = 'settings'
import SocketServer
from tracker.models import Position, Tracker
from protocols import GlobalsatReport


HOST = ''
PORT = 20100

class EchoRequestHandler(SocketServer.BaseRequestHandler ):
	def setup(self):
		print self.client_address, 'connected!'

	def handle(self):
		data = 'dummy'
		while 1:
			data = self.request.recv(1024)

			try:
				print u"data: %s" % str(data)
			except:
				print u'not printable data'

			if not data: break
			gr = GlobalsatReport(str(data))
			if not gr.IMEI:
				print "Not IMEI"
				continue
			if not gr.lon or not gr.lat:
				print "no coordinats"
				continue
			print 'lon: %s, lat: %s' % (gr.lon, gr.lat)
			tracker_qs = Tracker.objects.filter(IMEI=gr.IMEI)
			if not tracker_qs.count():
				print "Tracker with IMEI %s not found" % gr.IMEI
				continue
			tracker = tracker_qs[0]
			p = Position.objects.create(
										tracker = tracker,
										point = 'POINT(%1.6f %1.6f)' % (gr.longitude, gr.latitude),
										speed = gr.speed,)
			print "Position with id=%s created" % p.pk

			self.request.send("$OK!")

	def finish(self):
		print self.client_address, 'disconnected!'

server = SocketServer.ThreadingTCPServer((HOST, PORT), EchoRequestHandler)
server.serve_forever()

