#!/usr/bin/env python
import sys, os
sys.path.insert(1, os.path.join(sys.path[0], '..'))
sys.path.insert(1, os.path.join(sys.path[0], '../opengt'))
sys.path.insert(1, os.path.join(sys.path[0], '../..'))
sys.path.insert(1, os.path.join(sys.path[0], '../../..'))
os.environ['DJANGO_SETTINGS_MODULE'] = 'settings'
from tracker.models import Position

import socket
from protocols import GlobalsatReport

HOST = ''                 # Symbolic name meaning all available interfaces
PORT = 20100              # Arbitrary non-privileged port
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.bind((HOST, PORT))
s.listen(1)
conn, addr = s.accept()
print 'Connected by', addr
while 1:
	data = conn.recv(1024)
	print u"data: %s" % str(data)
	if not data: break
	gr = GlobalsatReport(str(data))
	print 'lon: %s, lat: %s' % (gr.lon, gr.lat)
	tracker_qs = Tracker.objects.filter(IMEI=gr.IMEI)
	if not tracker_qs.count():
		print "Tracker with imei %s not found" % gr.IMEI
		continue
	p = Position.objects.create(tracker=tracker, point='POINT(%1.6f %1.6f)' % (gr.longitude, gr.latitude))
	print "Position with id=%s created" % p.pk
	conn.send("$OK!")
conn.close()
